spring.application.name=ap4.exercicio
spring.datasource.url=jdbc:hsqldb:hsql://localhost:9001/mydb-exercicios
spring.datasource.username=sa
spring.datasource.password=
debug=false
spring.jpa.show-sql=false
spring.thymeleaf.cache=false