spring.application.name=ap3.exercicio
spring.datasource.url=jdbc:hsqldb:hsql://localhost:9001/mydb-exercicios
spring.datasource.username=sa
spring.datasource.password=
#debug=true
#spring.jpa.show-sql=true